name: customer_club
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  package_info_plus:
  cupertino_icons:
  flutter_secure_storage:
  top_snackbar_flutter:
  flutter_bloc:
  get_it:
  injectable: 
  flutter_svg:
  persian_number_utility:
  dio:
  dots_indicator:
  carousel_slider:
  url_launcher:
  cached_network_image: 
  maps_launcher: 
  flutter_osm_plugin: 0.70.4
  full_screen_image:
  animations:
  qr_code_scanner:
  image_picker:
  image_cropper:
  flutter_image_compress:
  path_provider:
  badges:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons:
  flutter_gen_runner:
  build_runner: 
  injectable_generator:
  
flutter_gen:
  output: lib/configs/gen
  integrations:
    flutter_svg: true
  
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/resources/logo.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  generate: true
  
  assets:
    - assets/resources/

  fonts:
    - family: Estedad
      fonts:
        - asset: assets/fonts/Estedad-Regular.ttf
