// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoglerD0OPs4zozfnuoRtlTHvqzDYtT3w',
    appId: '1:879121493549:android:8d2ea8f249d78d33bd52a4',
    messagingSenderId: '879121493549',
    projectId: 'revallpro',
    databaseURL: 'https://revallpro-default-rtdb.firebaseio.com',
    storageBucket: 'revallpro.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcdCFtKm3Cf3OAKwbFPKRoJI1sgnIeicU',
    appId: '1:879121493549:ios:f0c045ae29e9d290bd52a4',
    messagingSenderId: '879121493549',
    projectId: 'revallpro',
    databaseURL: 'https://revallpro-default-rtdb.firebaseio.com',
    storageBucket: 'revallpro.appspot.com',
    iosClientId:
        '879121493549-v6uev7arlu8k028i2aj2ljo5mjts2n9u.apps.googleusercontent.com',
    iosBundleId: 'com.revallpro.app',
  );
}
